
#' Power Generated by Reservoir
#'
#' This function determines the power generated by a given flow rate for a reservoir
#' @param height reservoir height (m)
#' @param flow rate (m/s)
#' @param rho density of water (kg/m3)
#' @param g acceleration due to gravity (m/s) default=9.8
#' @param Keff  reservoir efficiency (0-1) default 0.8
#' @return power (W)
#'
# function definition
power_gen_orig = function(height, flow, rho=1000, g=9.8, Keff=0.8) {
  result = rho * height * flow * g * Keff
  return(result)
}
